sudo: required
services:
  - docker

before_install:
  - docker build -t stefano2602/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stefano2602/react-test npm test

after_success:
  - docker build -t stefano2602/multi-container-client ./client
  - docker build -t stefano2602/multi-container-nginx ./nginx
  - docker build -t stefano2602/multi-container-server ./server
  - docker build -t stefano2602/multi-container-worker ./worker
  # login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push stefano2602/multi-container-client
  - docker push stefano2602/multi-container-nginx
  - docker push stefano2602/multi-container-server
  - docker push stefano2602/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: europe-central-1
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-eu-central-1-255205764285
  bucket_path: docker-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY